spring:
  cloud:
    nacos:
      discovery:
        namespace: ${config.register.namespace} # 命名空间
        server-addr: ${config.register.serverAddr} # 配置注册中心


feign: #远程连接
  hystrix: #熔断器配置
    enabled: true #启动熔断器