server:
  port: 8999

spring:
  cloud:
    nacos:
      discovery:
        namespace: ${config.register.namespace} # 命名空间
        server-addr: ${config.register.serverAddr} # 配置注册中心
  rabbitmq:
    host: ${config.mq.host} #rabbitMQ服务器地址
    port: ${config.mq.port}  #rabbitMQ服务器端口
    username: ${config.mq.username}
    password: ${config.mq.password}
    virtual-host: ${config.mq.virtual-host}

feign: #远程连接
  hystrix: #熔断器配置
    enabled: true #启动熔断器

#测试
words: 11111